// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Todo.Api.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Todo.Core.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assignee = "Daniel",
                            Description = "Bilen måste tvättas, vi har en rabattkod på TvättaDinBil i stan.",
                            IsComplete = false,
                            Title = "Tvätta bilen"
                        },
                        new
                        {
                            Id = 2,
                            Assignee = "Daniel",
                            Description = "Test",
                            IsComplete = false,
                            Title = "Köpa mjölk"
                        },
                        new
                        {
                            Id = 3,
                            Assignee = "Daniel",
                            Description = "Test",
                            IsComplete = false,
                            Title = "Köpa mjölk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
